version: 2
updates:

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    target-branch: develop

  - package-ecosystem: npm
    directory: web/
    schedule:
      interval: weekly
    target-branch: develop
