services:
  app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    environment:
      - JIOTV_DEBUG=true
      - JIOTV_PATH_PREFIX=/app/.jiotv_go
    ports:
      - 5001:5001
    volumes:
      - ./:/app
    env_file:
      - ./.env
