version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./:/app
      - jiotv_go:/apps/secrets
    env_file:
      - ./.env

volumes:
  jiotv_go: