name: ⭐ Feature request
description: Request a new feature or enhancement.
title: 'feat: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        # JioTV Go Feature request

        Important to note that your issue may have already been reported before. Please check for existing issues [here](https://github.com/jiotv-go/jiotv_go/labels/enhancement).
  - type: textarea
    attributes:
      label: Feature description
      description: What is the feature you would like to see added?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
    validations:
      required: false
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new and no duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I filled out all of the requested information in this issue properly.
          required: true