name: EPG Service

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # every day at 1:00am UTC (6:30am IST)

jobs:
  epg:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests xmltodict pysocks
      - name: Get EPG Data
        run: python ./scripts/epg.py ./assets/epg.xml.gz
      - name: pull latest
        run: |
          git pull
        # Commit all changed files back to the repository
      - name: Commit updated epg.xml
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated EPG
